# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler_to_trainer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ascheduler_to_trainer.proto\"\x13\n\x11QueryStatsRequest\"1\n\x12QueryStatsResponse\x12\x1b\n\x13\x66inished_iterations\x18\x01 \x01(\r2M\n\x12SchedulerToTrainer\x12\x37\n\nQueryStats\x12\x12.QueryStatsRequest\x1a\x13.QueryStatsResponse\"\x00\x62\x06proto3')



_QUERYSTATSREQUEST = DESCRIPTOR.message_types_by_name['QueryStatsRequest']
_QUERYSTATSRESPONSE = DESCRIPTOR.message_types_by_name['QueryStatsResponse']
QueryStatsRequest = _reflection.GeneratedProtocolMessageType('QueryStatsRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYSTATSREQUEST,
  '__module__' : 'scheduler_to_trainer_pb2'
  # @@protoc_insertion_point(class_scope:QueryStatsRequest)
  })
_sym_db.RegisterMessage(QueryStatsRequest)

QueryStatsResponse = _reflection.GeneratedProtocolMessageType('QueryStatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYSTATSRESPONSE,
  '__module__' : 'scheduler_to_trainer_pb2'
  # @@protoc_insertion_point(class_scope:QueryStatsResponse)
  })
_sym_db.RegisterMessage(QueryStatsResponse)

_SCHEDULERTOTRAINER = DESCRIPTOR.services_by_name['SchedulerToTrainer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYSTATSREQUEST._serialized_start=30
  _QUERYSTATSREQUEST._serialized_end=49
  _QUERYSTATSRESPONSE._serialized_start=51
  _QUERYSTATSRESPONSE._serialized_end=100
  _SCHEDULERTOTRAINER._serialized_start=102
  _SCHEDULERTOTRAINER._serialized_end=179
# @@protoc_insertion_point(module_scope)
