# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trainer_to_scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atrainer_to_scheduler.proto\"R\n\x16RegisterTrainerRequest\x12\x12\n\ntrainer_ip\x18\x01 \x01(\t\x12\x14\n\x0ctrainer_port\x18\x02 \x01(\r\x12\x0e\n\x06job_id\x18\x03 \x01(\r\"*\n\x17RegisterTrainerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"A\n\x12ReportStatsRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\x12\x1b\n\x13\x66inished_iterations\x18\x02 \x01(\r\"&\n\x13ReportStatsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x98\x01\n\x12TrainerToScheduler\x12\x46\n\x0fRegisterTrainer\x12\x17.RegisterTrainerRequest\x1a\x18.RegisterTrainerResponse\"\x00\x12:\n\x0bReportStats\x12\x13.ReportStatsRequest\x1a\x14.ReportStatsResponse\"\x00\x62\x06proto3')



_REGISTERTRAINERREQUEST = DESCRIPTOR.message_types_by_name['RegisterTrainerRequest']
_REGISTERTRAINERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterTrainerResponse']
_REPORTSTATSREQUEST = DESCRIPTOR.message_types_by_name['ReportStatsRequest']
_REPORTSTATSRESPONSE = DESCRIPTOR.message_types_by_name['ReportStatsResponse']
RegisterTrainerRequest = _reflection.GeneratedProtocolMessageType('RegisterTrainerRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERTRAINERREQUEST,
  '__module__' : 'trainer_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:RegisterTrainerRequest)
  })
_sym_db.RegisterMessage(RegisterTrainerRequest)

RegisterTrainerResponse = _reflection.GeneratedProtocolMessageType('RegisterTrainerResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERTRAINERRESPONSE,
  '__module__' : 'trainer_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:RegisterTrainerResponse)
  })
_sym_db.RegisterMessage(RegisterTrainerResponse)

ReportStatsRequest = _reflection.GeneratedProtocolMessageType('ReportStatsRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPORTSTATSREQUEST,
  '__module__' : 'trainer_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:ReportStatsRequest)
  })
_sym_db.RegisterMessage(ReportStatsRequest)

ReportStatsResponse = _reflection.GeneratedProtocolMessageType('ReportStatsResponse', (_message.Message,), {
  'DESCRIPTOR' : _REPORTSTATSRESPONSE,
  '__module__' : 'trainer_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:ReportStatsResponse)
  })
_sym_db.RegisterMessage(ReportStatsResponse)

_TRAINERTOSCHEDULER = DESCRIPTOR.services_by_name['TrainerToScheduler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERTRAINERREQUEST._serialized_start=30
  _REGISTERTRAINERREQUEST._serialized_end=112
  _REGISTERTRAINERRESPONSE._serialized_start=114
  _REGISTERTRAINERRESPONSE._serialized_end=156
  _REPORTSTATSREQUEST._serialized_start=158
  _REPORTSTATSREQUEST._serialized_end=223
  _REPORTSTATSRESPONSE._serialized_start=225
  _REPORTSTATSRESPONSE._serialized_end=263
  _TRAINERTOSCHEDULER._serialized_start=266
  _TRAINERTOSCHEDULER._serialized_end=418
# @@protoc_insertion_point(module_scope)
